name: 'modular_dbt_portfolio'
version: '1.0'
profile: 'modular_dbt_portfolio'
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]

models:
  modular_dbt_portfolio:
    +materialized: view
    bronze:
      +schema: bronze
      +tags: [bronze]
    silver:
      +schema: silver
      +tags: [silver]
    gold:
      +schema: gold
      +tags: [gold]
