version: 4

models:
  - name: staging__source_1__customers
    description: "Cleaned customers from source_1"
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: name
        description: "Customer full name"
  - name: staging__source_1__orders
    description: "Cleaned orders from source_1"
    columns:
      - name: id
        tests:
          - not_null
          - unique
  - name: staging__source_2__events
    description: "Cleaned events from source_2"
    columns:
      - name: event_id
        tests:
          - not_null
